name: tripi_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / estado
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0
  provider: ^6.1.2
  flutter_map_marker_popup: ^7.0.0

  # Networking
  dio: ^5.9.0

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.2.0

  # Media
  image_picker: ^1.2.0

  # Mapas (OpenStreetMap gratis)
  flutter_map: ^7.0.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/        # incluye todo lo de esa carpeta
    # o si prefieres específico:
    # - assets/icons/globe.png

